on:
  pull_request:
    branches:
      - core-1
name: Pull request workflow
jobs:
  validate_core1_assetlists:
    name: Validate assetlists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Asset List schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./assetlist.schema.json
          json_path_pattern: .*assetlist.json$